apiVersion: v1
kind: ConfigMap
metadata:
  name: upstashternal-coredns
  namespace: kube-system
data:
  Corefile: |
    upstashternal-dns.com:53 {
        upstashternal {}
    }
    .:53 {
        forward . /etc/resolv.conf
    } 