apiVersion: v1
kind: Service
metadata:
  name: upstashternal-coredns
  namespace: kube-system
spec:
  selector:
    app: upstashternal-coredns
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP 