apiVersion: v1
kind: ServiceAccount
metadata:
  name: upstashternal-dns
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: upstashternal-dns
rules:
- apiGroups: [""]
  resources: ["services", "pods", "endpoints"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["externaldns.k8s.io"]
  resources: ["dnsendpoints"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: upstashternal-dns
subjects:
- kind: ServiceAccount
  name: upstashternal-dns
  namespace: default
roleRef:
  kind: ClusterRole
  name: upstashternal-dns
  apiGroup: rbac.authorization.k8s.io 