apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: default
  annotations:
    upstashternal-dns.alpha.kubernetes.io/enabled: "true"
    upstashternal-dns.alpha.kubernetes.io/hostname: "test-service.upstashternal-dns.com"
spec:
  selector:
    app: test-app
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 8080